
# USDS
ROBOT_BODY_JOINT_NAME_DICT = {
    # 27 dofs
    "h1_2_with_hand_fix_links": [
        'pelvis', 'left_hip_yaw_link', 'right_hip_yaw_link', 
        'torso_link', 'left_hip_pitch_link', 'right_hip_pitch_link', 
        'left_shoulder_pitch_link', 'right_shoulder_pitch_link', 'left_hip_roll_link', 
        'right_hip_roll_link', 'left_shoulder_roll_link', 'right_shoulder_roll_link', 
        'left_knee_link', 'right_knee_link', 'left_shoulder_yaw_link', 
        'right_shoulder_yaw_link', 'left_ankle_pitch_link', 'right_ankle_pitch_link', 
        'left_elbow_link', 'right_elbow_link', 'left_ankle_roll_link', 
        'right_ankle_roll_link', 'left_wrist_roll_link', 'right_wrist_roll_link', 
        'left_wrist_pitch_link', 'right_wrist_pitch_link', 'left_wrist_yaw_link', 
        'right_wrist_yaw_link'],


    # 27 dofs
    "h1_2_with_hand_fix_joints": [
        'left_hip_yaw_joint', 'right_hip_yaw_joint', 'torso_joint', 
        'left_hip_pitch_joint', 'right_hip_pitch_joint', 'left_shoulder_pitch_joint', 
        'right_shoulder_pitch_joint', 'left_hip_roll_joint', 'right_hip_roll_joint', 
        'left_shoulder_roll_joint', 'right_shoulder_roll_joint', 'left_knee_joint', 
        'right_knee_joint', 'left_shoulder_yaw_joint', 'right_shoulder_yaw_joint', 
        'left_ankle_pitch_joint', 'right_ankle_pitch_joint', 'left_elbow_joint', 
        'right_elbow_joint', 'left_ankle_roll_joint', 'right_ankle_roll_joint', 
        'left_wrist_roll_joint', 'right_wrist_roll_joint', 'left_wrist_pitch_joint', 
        'right_wrist_pitch_joint', 'left_wrist_yaw_joint', 'right_wrist_yaw_joint'
        ],

    # 27 dofs
    "h1_2_with_hand_fix_payload_links": [
        'pelvis', 'left_hip_yaw_link', 'right_hip_yaw_link', 
        'torso_link', 'left_hip_pitch_link', 'right_hip_pitch_link', 
        'left_shoulder_pitch_link', 'right_shoulder_pitch_link', 'left_hip_roll_link', 
        'right_hip_roll_link', 'left_shoulder_roll_link', 'right_shoulder_roll_link', 
        'left_knee_link', 'right_knee_link', 'left_shoulder_yaw_link', 
        'right_shoulder_yaw_link', 'left_ankle_pitch_link', 'right_ankle_pitch_link', 
        'left_elbow_link', 'right_elbow_link', 'left_ankle_roll_link', 
        'right_ankle_roll_link', 'left_wrist_roll_link', 'right_wrist_roll_link', 
        'left_wrist_pitch_link', 'right_wrist_pitch_link', 'left_wrist_yaw_link', 
        'right_wrist_yaw_link'],


    # 27 dofs
    "h1_2_with_hand_fix_payload_joints": [
        'left_hip_yaw_joint', 'right_hip_yaw_joint', 'torso_joint', 
        'left_hip_pitch_joint', 'right_hip_pitch_joint', 'left_shoulder_pitch_joint', 
        'right_shoulder_pitch_joint', 'left_hip_roll_joint', 'right_hip_roll_joint', 
        'left_shoulder_roll_joint', 'right_shoulder_roll_joint', 'left_knee_joint', 
        'right_knee_joint', 'left_shoulder_yaw_joint', 'right_shoulder_yaw_joint', 
        'left_ankle_pitch_joint', 'right_ankle_pitch_joint', 'left_elbow_joint', 
        'right_elbow_joint', 'left_ankle_roll_joint', 'right_ankle_roll_joint', 
        'left_wrist_roll_joint', 'right_wrist_roll_joint', 'left_wrist_pitch_joint', 
        'right_wrist_pitch_joint', 'left_wrist_yaw_joint', 'right_wrist_yaw_joint'
        ],
}

# URDF
ROBOT_JOINT_NAME_DICT_URDF = {
    "h1_2_with_hand_fix_joints": [
        'left_hip_yaw_joint', 'left_hip_pitch_joint', 'left_hip_roll_joint', 
        'left_knee_joint', 'left_ankle_pitch_joint', 'left_ankle_roll_joint', 
        'right_hip_yaw_joint', 'right_hip_pitch_joint', 'right_hip_roll_joint', 
        'right_knee_joint', 'right_ankle_pitch_joint', 'right_ankle_roll_joint', 
        'torso_joint', 'left_shoulder_pitch_joint', 'left_shoulder_roll_joint', 
        'left_shoulder_yaw_joint', 'left_elbow_joint', 'left_wrist_roll_joint', 
        'left_wrist_pitch_joint', 'left_wrist_yaw_joint', 'right_shoulder_pitch_joint', 
        'right_shoulder_roll_joint', 'right_shoulder_yaw_joint', 'right_elbow_joint', 
        'right_wrist_roll_joint', 'right_wrist_pitch_joint', 'right_wrist_yaw_joint'
        ],
    "h1_2_with_hand_fix_payload_joints" : [
        'left_hip_yaw_joint', 'left_hip_pitch_joint', 'left_hip_roll_joint', 
        'left_knee_joint', 'left_ankle_pitch_joint', 'left_ankle_roll_joint', 
        'right_hip_yaw_joint', 'right_hip_pitch_joint', 'right_hip_roll_joint', 
        'right_knee_joint', 'right_ankle_pitch_joint', 'right_ankle_roll_joint', 
        'torso_joint', 'left_shoulder_pitch_joint', 'left_shoulder_roll_joint', 
        'left_shoulder_yaw_joint', 'left_elbow_joint', 'left_wrist_roll_joint', 
        'left_wrist_pitch_joint', 'left_wrist_yaw_joint', 'right_shoulder_pitch_joint', 
        'right_shoulder_roll_joint', 'right_shoulder_yaw_joint', 'right_elbow_joint', 
        'right_wrist_roll_joint', 'right_wrist_pitch_joint', 'right_wrist_yaw_joint'
    ]
}

ROBOT_JOINT_NAME_DICT_URDF_FOURIOR = {
    "fourior_with_hand_fix_joints": [
        'waist_roll_joint',
        'head_yaw_joint',
        'right_shoulder_pitch_joint',
        'right_shoulder_roll_joint',
        'right_shoulder_yaw_joint',
        'right_elbow_pitch_joint',
        'right_wrist_yaw_joint',
        'right_wrist_pitch_joint',
        'right_wrist_roll_joint',
        'left_shoulder_pitch_joint',
        'left_shoulder_roll_joint',
        'left_shoulder_yaw_joint',
        'left_elbow_pitch_joint',
        'left_wrist_yaw_joint',
        'left_wrist_pitch_joint',
        'left_wrist_roll_joint',
        'right_hip_pitch_joint',
        'right_hip_roll_joint',
        'right_hip_yaw_joint',
        'right_knee_pitch_joint',
        'right_ankle_pitch_joint',
        'right_ankle_roll_joint',
        'left_hip_pitch_joint',
        'left_hip_roll_joint',
        'left_hip_yaw_joint',
        'left_knee_pitch_joint',
        'left_ankle_pitch_joint',
        'left_ankle_roll_joint'
    ],

    "fourior_with_hand_fix_links": [
        'waist_roll_link',
        'head_yaw_link',
        'right_upper_arm_pitch_link',
        'right_upper_arm_roll_link',
        'right_upper_arm_yaw_link',
        'right_lower_arm_pitch_link',
        'right_hand_yaw_link',
        'right_hand_pitch_link',
        'right_hand_roll_link',
        'left_upper_arm_pitch_link',
        'left_upper_arm_roll_link',
        'left_upper_arm_yaw_link',
        'left_lower_arm_pitch_link',
        'left_hand_yaw_link',
        'left_hand_pitch_link',
        'left_hand_roll_link',
        'right_thigh_pitch_link',
        'right_thigh_roll_link',
        'right_thigh_yaw_link',
        'right_shank_pitch_link',
        'right_foot_pitch_link',
        'right_foot_roll_link',
        'left_thigh_pitch_link',
        'left_thigh_roll_link',
        'left_thigh_yaw_link',
        'left_shank_pitch_link',
        'left_foot_pitch_link',
        'left_foot_roll_link'
    ],

    "fourior_with_hand_fix_payload_joints" : [
        'left_hip_pitch_joint', 
        'left_hip_roll_joint',
        'left_hip_yaw_joint',   
        'left_knee_pitch_joint',
        'left_ankle_pitch_joint',
        'left_ankle_roll_joint',
        'right_hip_pitch_joint',
        'right_hip_roll_joint',
        'right_hip_yaw_joint',
        'right_knee_pitch_joint',
        'right_ankle_pitch_joint',
        'right_ankle_roll_joint',
        'waist_yaw_joint',
        'waist_roll_joint',
        'waist_pitch_joint',
        'head_yaw_joint',
        'head_pitch_joint',
        'left_shoulder_pitch_joint',
        'left_shoulder_roll_joint',
        'left_shoulder_yaw_joint',
        'left_elbow_pitch_joint',
        'left_wrist_yaw_joint',
        'left_wrist_pitch_joint',       
        'left_wrist_roll_joint',
        'right_shoulder_pitch_joint',
        'right_shoulder_roll_joint',
        'right_shoulder_yaw_joint',
        'right_elbow_pitch_joint',
        'right_wrist_yaw_joint',
        'right_wrist_pitch_joint',
        'right_wrist_roll_joint',
    ],

    "fourior_with_hand_fix_payload_links": [
        'left_hip_pitch_link', 
        'left_hip_roll_link',
        'left_hip_yaw_link',   
        'left_knee_pitch_link',
        'left_ankle_pitch_link',
        'left_ankle_roll_link',
        'right_hip_pitch_link',
        'right_hip_roll_link',
        'right_hip_yaw_link',
        'right_knee_pitch_link',
        'right_ankle_pitch_link',
        'right_ankle_roll_link',
        'waist_yaw_link',
        'waist_roll_link',
        'waist_pitch_link',
        'head_yaw_link',
        'head_pitch_link',
        'left_shoulder_pitch_link',
        'left_shoulder_roll_link',
        'left_shoulder_yaw_link',
        'left_elbow_pitch_link',
        'left_wrist_yaw_link',
        'left_wrist_pitch_link',       
        'left_wrist_roll_link',
        'right_shoulder_pitch_link',
        'right_shoulder_roll_link',
        'right_shoulder_yaw_link',
        'right_elbow_pitch_link',
        'right_wrist_yaw_link',
        'right_wrist_pitch_link',
        'right_wrist_roll_link',
    ]
}